### ISSUE TITLE
Scheduler crashbacklooping when no jobs

### ISSUE THREAD

**Issue by pjaak** [airflow-helm/charts#406]
**What is your question?**
HI Everyone!

Just a quick question... I have the 8.5.0 chart installed and I am using 2 scheduler containers. I have noticed that the probes on the scheduler pods check if there is any jobs alive and if not it will fail the checks and therefore restart the contains.

`Warning  Unhealthy  2m45s (x27 over 12h)  kubelet  Liveness probe failed: UNHEALTHY - 0 alive SchedulerJob for: airflow-scheduler-856668f6c4-hdgwx`

Is this intended? Sorry if I have missed something.

Ideally I would like them not the restart.

Thanks in advance!

**Comment by thesuperzapper** [comment]
@pjaak can you provide any custom `values.yaml` you are using.

Also, it might be best to use a clean Namespace for your install if your not already.

**Comment by pjaak** [comment]
Hey @thesuperzapper ,

There is no custom values really except the replicas and resources. Our airflow is busy on usually 1 day of the week and the other days doesn't schedule any jobs on other days(This is intended, we tend to run jobs on a weekend only). I can see from the probe which is set on schedulers that is seems it is intended to sys.exit if no jobs are alive.

`sys.exit(f"UNHEALTHY - {count_alive_jobs} (more than 1) alive SchedulerJob for: {hostname}")`

Is it intended to fail the probes if there is no jobs alive? and therefore end up in crashbackloop?

I might be missing how the scheduler works. Does the probe check if the airflow scheduler service itself is running? Or if there is jobs/tasks in the queue?

Thanks,

**Comment by thesuperzapper** [comment]
@pjaak the livenessProbe detects if there is a [SchedulerJob](https://github.com/apache/airflow/blob/2.1.3/airflow/jobs/scheduler_job.py#L73) running, airflow uses these to check the health of the scheduler, there should always be exactly one `SchedulerJob` for each scheduler.

I am interested to know why it can't see your `SchedulerJob`, perhaps it's something to do with the hostname (as we [filter by hostname](https://github.com/airflow-helm/charts/blob/f1234145a9455ac7848631d433bfdf926080b891/charts/airflow/templates/scheduler/scheduler-deployment.yaml#L140))?

_BTW: if this is affecting your production system, you can disable the probe with `scheduler.livenessProbe.enabled`_

**Comment by pjaak** [comment]
@thesuperzapper its very odd...

I ran the python healthcheck on a container manually and sometimes get this:
`airflow@airflow-scheduler-856668f6c4-z8qrh:/opt/airflow$ python test.py
airflow-scheduler-856668f6c4-z8qrh
[]
[]
UNHEALTHY - 0 alive SchedulerJob for: airflow-scheduler-856668f6c4-z8qrh
airflow@airflow-scheduler-856668f6c4-z8qrh:/opt/airflow$`

Sometimes I get this:
'airflow@airflow-scheduler-856668f6c4-z8qrh:/opt/airflow$ python test.py
airflow-scheduler-856668f6c4-z8qrh
[<airflow.jobs.scheduler_job.SchedulerJob object at 0x7fc246a21f70>]
airflow@airflow-scheduler-856668f6c4-z8qrh:/opt/airflow$'

I just added some print lines in to debug... Is it safe to turn off the livenessprobe tho? What does it mean if there is no scheduler job running at some points in time.

We have about 120 dags and each dag can have thousands of tasks, not sure if this makes a difference.
Would changing this value do anything aswell?

AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_THRESHOLD

Thanks

**Comment by thesuperzapper** [comment]
@pjaak can you figure out what is causing `count_alive_jobs` in the health check to be `0` (by running directly on the pod)?

For example, is it that there are no `State.RUNNING` SchedulerJobs for the `hostname` OR, is it that all fail the `is_alive()` check?

```
import sys
from typing import List
from airflow.jobs.scheduler_job import SchedulerJob
from airflow.utils.db import create_session
from airflow.utils.net import get_hostname
from airflow.utils.state import State
with create_session() as session:
    hostname = get_hostname()
    query = session \
        .query(SchedulerJob) \
        .filter_by(state=State.RUNNING, hostname=hostname) \
        .order_by(SchedulerJob.latest_heartbeat.desc())
    
    jobs: List[SchedulerJob] = query.all()
    alive_jobs = [job for job in jobs if job.is_alive()]
    count_alive_jobs = len(alive_jobs)

if count_alive_jobs == 1:
    # scheduler is healthy - we expect one SchedulerJob per scheduler
    pass
elif count_alive_jobs == 0:
    sys.exit(f"UNHEALTHY - 0 alive SchedulerJob for: {hostname}")
else:
    sys.exit(f"UNHEALTHY - {count_alive_jobs} (more than 1) alive SchedulerJob for: {hostname}")
```

**Comment by pjaak** [comment]
So i added some print statements to the livenessprobe,

`Liveness probe failed: Jobs in State.RUNNING: 1, Alive jobs from the running jobs: 0`

I noticed everytime the container restarts the State.RUNNING numbers goes up by 1.. for example:

`Liveness probe failed: Jobs in State.RUNNING: 2, Alive jobs from the running jobs: 0`

It looks like it is failing the is_alive() check.... Any ideas?

Here is my basic code that I added:
```
                  import sys
                  from typing import List
                  from airflow.jobs.scheduler_job import SchedulerJob
                  from airflow.utils.db import create_session
                  from airflow.utils.net import get_hostname
                  from airflow.utils.state import State

                  with create_session() as session:
                      hostname = get_hostname()
                      query = session \
                          .query(SchedulerJob) \
                          .filter_by(state=State.RUNNING, hostname=hostname) \
                          .order_by(SchedulerJob.latest_heartbeat.desc())
                      jobs: List[SchedulerJob] = query.all()
                      alive_jobs = [job for job in jobs if job.is_alive()]
                      count_alive_jobs = len(alive_jobs)

                  if count_alive_jobs == 1:
                      # scheduler is healthy - we expect one SchedulerJob per scheduler
                      pass
                  elif count_alive_jobs == 0:
                      print("Jobs running for hostname: " + str(len(jobs)) + ", Alive jobs from the running jobs: " + str(count_alive_jobs))
                      sys.exit(f"UNHEALTHY - 0 alive SchedulerJob for: {hostname}")
                  else:
                      print("Jobs running for hostname: " + str(len(jobs)) + ", Alive jobs from the running jobs: " + str(count_alive_jobs))
                      sys.exit(f"UNHEALTHY - {count_alive_jobs} (more than 1) alive SchedulerJob for: {hostname}")
```

**Comment by mholtzscher** [comment]
@pjaak any update on this? I'm seeing the same issue

**Comment by thesuperzapper** [comment]
@mholtzscher I have a suspicion it's related to the `scheduler.livenessProbe.timeoutSeconds` value being too low.

I have seen reports that when users upgrade to Kubernetes `1.20+` this starts happening, as it seems that `timeoutSecions` [was not respected in `exec` probes in `1.19` and before](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes).

----

I will push a hot-patch for the chart which changes the default `scheduler.livenessProbe.timeout` seconds to `60`.

Also, it's probably a good idea to increase the other `timeoutSeconds` for `exec` probes:
- `scheduler.livenessProbe.timeout` (old: `10`, new: `60`)
- `flower.readinessProbe.timeoutSeconds` (old: `5`, new: `30`)
- `flower.livenessProbe.timeoutSeconds`  (old: `5`, new: `30`)
- `pgbouncer.livenessProbe.timeoutSeconds` (old: `15`, new: `60`)

**Comment by thesuperzapper** [comment]
@mholtzscher I have raised an issue to track this hot-patch: https://github.com/airflow-helm/charts/issues/484

**Comment by thesuperzapper** [comment]
@pjaak I would love to know if increasing `scheduler.livenessProbe.timeoutSeconds` resolves your issue?

Also, what version of Kubernetes you are on?

**Comment by mholtzscher** [comment]
@thesuperzapper I just deployed the updated timeoutSeconds to a dev cluster to test. I'll post back in a day or so with results

**Comment by victorszatta** [comment]
@mholtzscher do you have any updates regarding this issue? I'm also with this same problem, tried different combinations of airflow variables values, but I can't find the problem. I also uninstalled and redeployed the whole solution, but the error persists. Our airflow DB connections and resources do not appears to be the problem. Running airflow 2.1.4 with python3.8.

**Comment by mholtzscher** [comment]
@thesuperzapper CC: @victorszatta I two and half days now and only had 1 restart ( that might of been me changing another config). We were at around 90 restarts a day so this seems to of resolved our issue

**Comment by victorszatta** [comment]
OK, I found the reason my scheduler was breaking. I had set the `airflow.image.gid` to 50000 and `airflow.image.uid` to 50000. 
I just reseted the `airflow.image.gid` to 0 and now the scheduler is working fine. I don't think is directly related to the problem on this thread, but might help someone.

The thing is I always used that same value and never had a problem. I can't explain why it started to happen, but if I had to guess: I use an Azure File Share for the DAGs repository and mounted it as PVC and something might have changed on that side.

**Comment by thesuperzapper** [comment]
> @thesuperzapper CC: @victorszatta I have run this for two and half days now and only had 1 restart ( that might of been me changing another config). We were at around 90 restarts a day so this seems to of resolved our issue.
> 
> To be clear I only updated:
> 
> `scheduler.livenessProbe.timeoutSeconds (old: 10, new: 60)`

@mholtzscher thanks for confirming this, I have gone ahead a pushed out patch release [`8.5.3`](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md#853---2022-01-10) which increases the default `timeoutSeconds` to `60` seconds.

**Comment by sharonsahadevan** [comment]
We are using Airflow 2.6.2 and we have more than 300 DAGS. Timeout seconds 120. But I still see restarts.
